sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ZI2dcFt6VUB4xRSi1VIK3CXDC1gtq1rsflEqe3YSzaillE6P57zuHNDYgv/zCK1+/TGn0wSKHLQfp+Dh0fTgrOV/CenwpHWRmqR1YMKN7aI/rHsslaJrarRqJGA40dAVjaKAtJ/9FnmQw7RlTPR8lwMpAzP2jmrae464CetYn3mPf+IXjLoXsO/u/GymPQiU3CJC6NHeKZzADBFyPV8d0BxPhl2cqo97WA5Wb8dzEdEz5Owhu8yImEwho+w7KMPaixH7PEwfZ6irawD6hEdIGgoIfrFMS1toK9cnM8G0YNKf3Li+T+0AWYWOzqFYwvJWxNKpK6REMGv0NdV6XI42x3csXIeK/r5pAmHhoa6J7btZmr94Lwv+XxrUsa99/Nq/JDYUNy856RzUaIDJHznMW4qce7M4J0wnqPRYw6IKNXtNxGIGV2ypRNLfn5XOQmgKQICcpum73yaEmgF8/tZvFkUk9BA57IrOOZD27ObWr+sOh8NTw18Ha9jtrJxgIGm1nCkNzoYP3yamo0NAtrTjj8XHl3+xE4nFEBQ6XOXUfE7CcDg+NCklPjZiKu4lyIGdlr/4DpxMS+GwA0+4mBGjFsaA3zaQW1lVactDtk2lIXZEBgVG3qLT26xc80zaNEglMLavBWtB2CfoSrPyCl+TjyqmhYrJF7ziagOreoVGpuU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Essays-of-Michel-de-Montaigne---Volume-11_3591
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy